const DEFAULT_STRINGS = Object.freeze({
  name: 'TestLoop Sample',
  title: 'TestLoop Sample',
  description: 'Generated by TestLoop',
  email: 'testloop@example.invalid',
  phone: '+10000000000'
});

export function buildFixturePlan({ requestModel, validator = null, supplied = {}, reusableFixtures = {} }) {
  if (!requestModel?.name || !Array.isArray(requestModel.properties)) {
    throw new Error('A request model with properties is required.');
  }

  const validatorRules = new Map((validator?.rules ?? []).map(rule => [rule.property, rule.constraints ?? []]));
  const dependencies = new Map((requestModel.dependencies ?? []).map(item => [item.property, item]));
  const payload = {};
  const resolutions = [];
  const blocked = [];

  for (const property of requestModel.properties) {
    const dependency = dependencies.get(property.name);
    if (dependency) {
      const reusable = reusableFixtures[property.name] ?? reusableFixtures[dependency.entity];
      if (reusable?.verified === true && reusable.value !== undefined && reusable.source !== 'random') {
        payload[property.name] = reusable.value;
        resolutions.push({
          property: property.name,
          source: reusable.source,
          verified: true,
          entity: dependency.entity,
          evidence: reusable.evidence ?? []
        });
      } else {
        blocked.push({
          property: property.name,
          entity: dependency.entity,
          reason: dependency.entity
            ? `Verified ${dependency.entity} fixture is required.`
            : 'Persisted dependency could not be mapped to an entity.',
          suppliedValueIgnored: Object.hasOwn(supplied, property.name),
          allowedSources: ['workflow-output', 'seed', 'safe-read-endpoint', 'test-database', 'producer-endpoint']
        });
      }
      continue;
    }

    if (Object.hasOwn(supplied, property.name)) {
      payload[property.name] = supplied[property.name];
      resolutions.push(resolution(property.name, 'supplied', true));
      continue;
    }

    const generated = generateScalar(property, validatorRules.get(property.name) ?? []);
    if (generated.supported) {
      payload[property.name] = generated.value;
      resolutions.push(resolution(property.name, 'deterministic-generator', true, generated.notes));
    } else if (property.required) {
      blocked.push({ property: property.name, entity: null, reason: generated.reason, allowedSources: ['supplied'] });
    }
  }

  return {
    requestType: requestModel.name,
    status: blocked.length === 0 ? 'READY' : 'BLOCKED',
    payload,
    resolutions,
    blocked,
    fixtureManifest: {
      dependencies: resolutions
        .filter(item => dependencies.has(item.property))
        .map(item => ({ property: item.property, source: item.source, verified: item.verified }))
    }
  };
}

export function selectFixtureCandidate(candidates, predicates = []) {
  const accepted = candidates.filter(candidate => predicates.every(predicate => evaluatePredicate(candidate, predicate)));
  if (accepted.length === 0) return null;
  return accepted
    .slice()
    .sort((left, right) => stableKey(left).localeCompare(stableKey(right)))[0];
}

function generateScalar(property, constraints) {
  const type = property.type.replace(/\?$/, '').toLowerCase();
  const name = property.name.toLowerCase();

  if (type === 'string') {
    let value = DEFAULT_STRINGS[name] ?? (name.includes('email') ? DEFAULT_STRINGS.email : name.includes('phone') ? DEFAULT_STRINGS.phone : `${property.name} Test`);
    const min = constraintValue(constraints, 'min-length');
    const max = constraintValue(constraints, 'max-length');
    if (min && value.length < min) value = value.padEnd(min, 'x');
    if (max && value.length > max) value = value.slice(0, max);
    return { supported: true, value, notes: constraints };
  }

  if (['int', 'int32', 'int64', 'long', 'short', 'decimal', 'double', 'float'].includes(type)) {
    const greaterThan = constraintValue(constraints, 'greater-than');
    return { supported: true, value: greaterThan !== null ? greaterThan + 1 : 1, notes: constraints };
  }

  if (type === 'bool' || type === 'boolean') return { supported: true, value: true, notes: [] };
  if (type === 'datetime' || type === 'datetimeoffset') return { supported: true, value: '2030-01-01T12:00:00Z', notes: [] };
  if (type.startsWith('list<') || type.endsWith('[]') || type.startsWith('ienumerable<')) return { supported: true, value: [], notes: [] };
  if (type === 'guid') return { supported: false, reason: `Guid property ${property.name} requires semantic classification before generation.` };

  return { supported: false, reason: `No deterministic generator exists for ${property.type}.` };
}

function evaluatePredicate(candidate, predicate) {
  const actual = candidate?.[predicate.property];
  switch (predicate.operator) {
    case 'equals': return actual === predicate.value;
    case 'not-equals': return actual !== predicate.value;
    case 'truthy': return Boolean(actual);
    case 'falsy': return !actual;
    case 'in': return Array.isArray(predicate.value) && predicate.value.includes(actual);
    default: throw new Error(`Unsupported predicate operator: ${predicate.operator}`);
  }
}

function constraintValue(constraints, type) {
  return constraints.find(item => item.type === type)?.value ?? null;
}

function resolution(property, source, verified, evidence = []) {
  return { property, source, verified, evidence };
}

function stableKey(candidate) {
  return String(candidate?.id ?? candidate?.Id ?? JSON.stringify(candidate));
}
